apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway
  namespace: quarto
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-manager
  namespace: quarto
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-pod-manager
  namespace: quarto
subjects:
  - kind: ServiceAccount
    name: gateway
    namespace: quarto
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io
