apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quarto

resources:
  - ../../base

images:
  - name: quarto-gateway
    newName: k3d-quarto-registry:5000/quarto-server
    newTag: gateway-latest
  - name: quarto-editor
    newName: k3d-quarto-registry:5000/quarto-server
    newTag: editor-latest
